name: Run ndpjs-min

on:
  schedule:
    - cron: "*/20 * * * *" # Runs every 20 minutes
  workflow_dispatch: # Allows manual run of the workflow

concurrency:
  group: ndjs-group
  cancel-in-progress: true

jobs:
  run-ndpmjs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Using Node.js 18 LTS

    - name: Install dependencies
      run: |
        npm install

    - name: Fetch proxies and create proxies.txt
      run: |
        urls=(
          "https://raw.githubusercontent.com/shahid0/super-duper-octo-winner/refs/heads/main/us_working_proxies.txt"
          "https://raw.githubusercontent.com/shahid0/super-duper-octo-winner/refs/heads/main/working_proxies.txt"
        )
        > proxy.txt
        for url in "${urls[@]}"; do
          echo "Fetching proxies from $url"
          if curl -s "$url" >> proxy.txt; then
            echo "Fetched successfully."
          else
            echo "Failed to fetch from $url" >&2
          fi
        done
        echo "Proxies fetched and saved to proxy.txt"
        # Remove empty lines and duplicates
        sed -i '/^[[:space:]]*$/d' proxy.txt
        sort -u proxy.txt -o proxy.txt
        # echo "Validated proxies:"
        # cat proxy.txt

    - name: Create np_tokens.txt with secret value
      env:
        DATA_SECRET: ${{ secrets.DATA }}
      run: |
        if [[ -z "$DATA_SECRET" ]]; then
          echo "Error: Secret DATA is empty." >&2
          exit 1
        fi
        echo "$DATA_SECRET" > token.txt
        echo "Secret written to token.txt"

    - name: Run Node.js script
      run: |
        if [[ ! -s proxies.txt ]]; then
          echo "Error: proxies.txt is empty or missing." >&2
          exit 1
        fi
        npm run start
      env:
        NODE_NO_WARNINGS: '1' # Suppress deprecation warnings
